import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();
  const { data } = api.posts.getAll.useQuery();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          {!user.isSignedIn && (
            <div>
              <h1> Sign in </h1>
              <SignInButton redirectUrl="/home/" />
            </div>
          )}
          {!!user.isSignedIn && (
            <div>
              <h1> Sign Out </h1>
              <SignOutButton />
            </div>
          )}
        </div>
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />

        <div>
          {data?.map((post) => (
            <div key={post.id}>
              <h1>{post.content}</h1>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
